steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'britishglobal-webhook'
      - '--source'
      - '.'
      - '--region=europe-west2'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--timeout=300'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--cpu=1'
      - '--concurrency=10'
      - '--set-env-vars=FLASK_ENV=production,PORT=8080'
timeout: '900s'